### ISSUE TITLE
Lofo offer for Prayer-Notifier

### ISSUE THREAD

**Issue by familqasimov** [AAli9400/Prayer-Notifier#1]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/40281094-d63ffbee-5c6d-11e8-9dcb-273fcab8fd72.png)

Best regard
Famil. :)

**Comment by AAli9400** [comment]
Hello Famil,
Thank you for your time and offer.
I have most of the required resources for this app, 
the overall app design is going to be changed completely. also, it's too soon to choose the app logo.

Thank you 😁
